name: Security Scan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checkov:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/security-checkov.yml@v2
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1, CKV_AZURE_244, CKV_AZURE_59, CKV_AZURE_33, CKV_AZURE_206, CKV_AZURE_112, CKV_AZURE_190, CKV_AZURE_35, CKV_AZURE_36, CKV2_AZURE_40, CKV2_AZURE_47, CKV2_AZURE_8, CKV2_AZURE_20, CKV2_AZURE_21, CKV2_AZURE_33, CKV_AZURE_134, CKV_AZURE_236, CKV2_AZURE_22'