name: Security Scan

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@88efd7724e007c8f721a219498be29e0c9ad471b
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1,CKV2_AZURE_20,CKV2_AZURE_21,CKV2_AZURE_33,CKV2_AZURE_40,CKV2_AZURE_47,CKV2_AZURE_8,CKV_AZURE_112,CKV_AZURE_190,CKV_AZURE_206,CKV_AZURE_244,CKV_AZURE_33,CKV_AZURE_35,CKV_AZURE_36,CKV_AZURE_59'