name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/basic/'

  cmk-enabled-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/cmk_enable/'

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'

  private-endpoint-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/private_endpoint/'

  static-website-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/static_website/'
  
# Seperate Job for TFlint workflow call
  tf-lint:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-lint.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
